# Generated by Django 2.0.5 on 2018-06-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=200, unique=True)),
                ('concept_description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Relations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_government', models.FloatField(default=0)),
                ('role_company', models.FloatField(default=0)),
                ('role_household', models.FloatField(default=0)),
                ('role_central_bank', models.FloatField(default=0)),
                ('action_production', models.FloatField(default=0)),
                ('action_distribution', models.FloatField(default=0)),
                ('action_consumption', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField(default=0)),
                ('sum_x_square', models.FloatField(default=0)),
                ('sum_x', models.FloatField(default=0)),
                ('var_x', models.FloatField(default=0)),
                ('selected', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='relations',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classifier.Relations'),
        ),
        migrations.AddField(
            model_name='concept',
            name='statistics',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classifier.Statistics'),
        ),
    ]
